name: "SLZ-GCP"

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "This is a placeholder"
  workingDirectory: '$(Build.Repository.LocalPath)'
  displayName: 'Placeholder Task'

# # Send to release pipeline to deploy to environment
# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     ArtifactName: 'gcp_tf'
#     publishLocation: 'Container'
